import type { Metadata } from "next";
import { Kaisei_Decol } from "next/font/google";
import "./globals.css";
import SaleProvider from "@/components/contextSale/saleProvider";

const KaiseiDecol = Kaisei_Decol({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-kaisei',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${KaiseiDecol.variable} antialiased`}
      >
        <SaleProvider>
          {children}
        </SaleProvider>
      </body>
    </html>
  );
}
